apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: spark-operator
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: BogdanLab2
        - name: TZ
          value: Europe/Moscow
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P BogdanLab2
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc
        
