# https://github.com/kubeflow/spark-operator/blob/master/examples/spark-py-pi.yaml

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: lab5
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "bogdanliutikov/lab5:latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/main.py
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 2
    memory: "2g"
    labels:
      version: 3.5.1
    serviceAccount: spark
  executor:
    cores: 5
    instances: 3
    memory: "4g"
    labels:
      version: 3.5.1